on:
  push:
  pull_request:

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check artifact
        shell: cmd
        run: scripts/check_artifact.cmd
